apiVersion: v1
kind: Pod
spec:
  containers:
    - name: golang
      image: golang:1.17
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: 3Gi
          cpu: "2"
        limits:
          memory: 5Gi
      imagePullPolicy: Always
    - name: my-image
      image: registry/image:1.0.0
      command:
        - cat
      tty: true
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2376
        - name: DOCKER_TLS_VERIFY
          value: "1"
        - name: DOCKER_CERT_PATH
          value: /certs/client
      volumeMounts:
        - name: docker-client-certs
          mountPath: /certs/client
      resources:
        requests:
          memory: 256Mi
          cpu: 50m
        limits:
          memory: 512Mi
      imagePullPolicy: Always
    - name: dind
      image: docker:19.03.6-dind
      env:
        - name: DOCKER_TLS_CERTDIR
          value: /certs
      volumeMounts:
        - name: docker-client-certs
          mountPath: /certs/client
        - name: docker-config
          mountPath: /etc/docker/daemon.json
          subPath: daemon.json
      securityContext:
        privileged: true
      resources:
        requests:
          memory: 1Gi
          cpu: "1"
        limits:
          memory: 2Gi
      imagePullPolicy: Always
  volumes:
    - name: docker-client-certs
      emptyDir:
        medium: Memory
    - name: docker-config
      configMap:
        name: docker-config
